name: interacttester_app
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.9.0
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.4.4
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  cloud_firestore: ^0.12.9+5
  path_provider: ^2.0.0
  http: ^0.13.0
  google_fonts: ^2.0.0
  cupertino_icons: ^0.1.3
  url_launcher: ^5.7.10
  image_picker: ^0.6.6
  firebase_storage: ^3.1.6
  permission_handler: ^5.0.1+1
  gsheets: ^0.3.0
  share:
    git:
      url: git://github.com/himanshusharma89/plugins.git
      path: packages/share
  photo_manager: ^0.5.8
  video_player: ^0.11.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
